openapi: 3.0.0
info:
  title: 'REST API Docs'
  version: '1.0'
paths:
  /users:
    get:
      tags:
        - Users
      summary: 'Get all list of users'
      operationId: 1b8a72edec98e8e06702e1fb8a052366
      responses:
        '200':
          description: Success
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Users
      summary: 'Add a new user'
      description: 'Returns a single user'
      operationId: store
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - name
                - email
                - gender
                - status
              properties:
                name:
                  type: string
                email:
                  type: string
                gender:
                  type: string
                  default: male
                  enum: [male, female]
                status:
                  type: string
                  default: active
                  enum: [active, inactive]
              type: object
      responses:
        '200':
          description: Success
      security:
        -
          bearerAuth: []
  '/users/{userId}':
    get:
      tags:
        - Users
      summary: 'Find user by ID'
      description: 'Returns a single user'
      operationId: show
      parameters:
        -
          name: userId
          in: path
          description: 'ID of user to return'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
      security:
        -
          bearerAuth: []
    post:
      tags:
        - Users
      summary: 'Delete user'
      operationId: delete
      parameters:
        -
          name: userId
          in: path
          description: 'User id to delete'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Success
      security:
        -
          bearerAuth: []
  /users/update:
    post:
      tags:
        - Users
      summary: 'Update user'
      description: 'Updates a single user'
      operationId: update
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - id
                - name
                - email
                - gender
                - status
              properties:
                id:
                  type: string
                name:
                  type: string
                email:
                  type: string
                gender:
                  type: string
                  default: male
                  enum: [male, female]
                status:
                  type: string
                  default: active
                  enum: [active, inactive]
              type: object
      responses:
        '200':
          description: Success
      security:
        -
          bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      name: bearerAuth
      in: header
      bearerFormat: JWT
      scheme: bearer
